name: desk_pilot_f
description: DeskPilotF - Next-generation desktop productivity environment
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.5.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
